// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
#define _FL 0
#define _SL 1
#define _TL 2
#define _GL 3

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_FL] = LAYOUT(
        KC_ESC,     KC_1,      KC_2,       KC_3,           KC_4,     KC_5,     KC_6,
        KC_GRAVE,   KC_Q,      KC_W,       KC_E,           KC_R,     KC_T,     KC_Y,
        KC_TAB,     KC_A,      KC_S,       KC_D,           KC_F,     KC_G, 
        KC_LSFT,    KC_Z,      KC_X,       KC_C,           KC_V,     KC_B,     KC_LEFT,
		KC_LCTL,    KC_APP,    KC_LALT,    KC_BACKSPACE,   KC_SPC,   KC_ENT,
                                                                     MO(_FL),  KC_RGHT,
   

        KC_7,      KC_8,      KC_9,      KC_0,      KC_MINS,  KC_EQL,   KC_BACKSPACE,
        KC_U,      KC_I,      KC_O,      KC_P,      KC_LBRC,  KC_RBRC,  KC_BSLS,
                   KC_H,      KC_J,      KC_K,      KC_L,     _______,  _______,
		KC_N,      KC_M,      _______,   _______,   _______,  _______,  KC_LEFT,
		KC_DOWN,   KC_UP,     KC_RGHT,   _______,   _______,  KC_A,
        _______,   KC_RCTL
    ),
	[_SL] = LAYOUT(
	KC_CALCULATOR, KC_AUDIO_MUTE,
	KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP,
	KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE,
	KC_MEDIA_NEXT_TRACK, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______,
	KC_CALCULATOR, KC_AUDIO_MUTE,
	KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP,
	KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE,
	KC_MEDIA_NEXT_TRACK, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______
	),
	[_TL] = LAYOUT(
	KC_CALCULATOR, KC_AUDIO_MUTE,
	KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP,
	KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE,
	KC_MEDIA_NEXT_TRACK, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______,
	KC_CALCULATOR, KC_AUDIO_MUTE,
	KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP,
	KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE,
	KC_MEDIA_NEXT_TRACK, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______
	),
	[_GL] = LAYOUT(
	KC_CALCULATOR, KC_AUDIO_MUTE,
	KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP,
	KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE,
	KC_MEDIA_NEXT_TRACK, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______,
	KC_CALCULATOR, KC_AUDIO_MUTE,
	KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP,
	KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE,
	KC_MEDIA_NEXT_TRACK, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______, _______,
	_______
	)
	
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_FL] = { ENCODER_CCW_CW(KC_MINS, KC_EQL) },
    [_SL] = { ENCODER_CCW_CW(UG_HUED, UG_HUEU) },
    [_TL] = { ENCODER_CCW_CW(UG_VALD, UG_VALU) },
    [_GL] = { ENCODER_CCW_CW(UG_PREV, UG_NEXT) },
};
#endif
